### ISSUE TITLE
Allow passing a color to default

### ISSUE THREAD

**Issue by tommoor** [tommoor/tiley#20]
In some circumstances it is nice to be able to bypass the palette and choose a specific color for the avatar directly. We should allow a `color` parameter that will override the default.

**Comment by ClemMakesApps** [comment]
I assume this is for the background color? And this would be a similar implementation to the `size` parameter?

**Comment by tommoor** [comment]
@ClemMakesApps that's correct - the background color and similar implementation to the size parameter yep. 

We'd also need to update the README to reflect the new param once implemented!

**Comment by ClemMakesApps** [comment]
Sounds good. What are your thoughts on a parameter to change the text color?

**Comment by tommoor** [comment]
Closed by 83a151467808f4c9f0dfa1b1b9b49b2b7c3d794d
