### ISSUE TITLE
Size does not change on SVG

### ISSUE THREAD

**Issue by ClemMakesApps** [tommoor/tiley#22]
The size of the SVG does not change even though it is given a size parameter.

<img width="662" alt="screen shot 2016-10-03 at 11 06 18 am" src="https://cloud.githubusercontent.com/assets/3363898/19044357/7fe50066-8959-11e6-86fb-3846d357274b.png">

**Comment by ClemMakesApps** [comment]
I have a PR in the works for this!

**Comment by abhishekg785** [comment]
i will like to work on this !
